bingoGenerator = require("./generators/generator_bases/simple_generator.js");

var bingoList = [
  "Complete All of Pirates Island",
  "Complete All of Forest Village",
  "Complete All of Dino Mountain",
  "Complete All of Blizzard Castle",
  "Complete All of Circus Park",
  "Complete All of Sand Ruins",
  "Complete All of Giant Palace",
  "Collect 20 Chick Coins in Forest Village",
  "Collect 20 Chick Coins in Pirates Island",
  "Collect 20 Chick Coins in Dino Mountain",
  "Collect 20 Chick Coins in Blizzard Castle",
  "Collect 20 Chick Coins in Circus Park",
  "Collect 20 Chick Coins in Sand Ruins",
  "Collect 20 Chick Coins in Giant Palace",
  "Beat 3 Bantam Missions",
  "Beat 3 Chick Missions",
  "Beat 3 Rolly Missions",
  "Uncover Billys true identity",
  "Uncover Chicks true identity",
  "Hatch Chao",
  "Life counter reaches 35",
  "Hatch 5 Unique Animal Buddies",
  "Hatch 3 Unique Mountable Animal Buddies",
  "Hatch Super Recky and Super Clippen",
  "Hit 1 Mystery Switch",
  "Hatch Both Butterflies",
  "Hatch 1 Gameboy Game Egg",
  "Get S Rank in 15 Levels",
  "Get 4 S Ranks in Forest Village",
  "Get 4 S Ranks in Pirates Island",
  "Get 4 S Ranks in Dino Mountain",
  "Get 4 S Ranks in Blizzard Castle",
  "Get 4 S Ranks in Circus Park",
  "Get 4 S Ranks in Sand Ruins",
  "Get 3 S Ranks in Giant Palace",
  "Collect 50 Chick Coins",
  "Collect 25 Chick Coins in Friend Levels",
  "Collect 15 Chick Coins in Rolly Levels",
  "Collect 15 Chick Coins in Chick Levels",
  "Collect 15 Chick Coins in Bantam Levels",
  "Get Kicked out of Sand 3",
  "Die in the Fog room in Sand 7",
  "Complete 3 100 Crow Levels",
  "Complete 3 Save the 8 Chicken Levels",
  "Complete 3 Minigame Levels",
  "Complete 4 Race Levels",
  "Get a Scramble Combo",
  "Get an Omlette Combo",
  "Hatch a 1-UP Egg in every World",
  "Hatch a Crow and a Bat",
  "Hatch 3 Unique Comb Eggs",
  "Hatch 5 Unique Equipment",
  "Get bomb hyperspeed",
];